# 2022-03-07 19:06:11.472149: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory2022-03-07 19:06:11.472194: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.2022-03-07 19:06:12.381594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory2022-03-07 19:06:12.381640: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)2022-03-07 19:06:12.381661: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (devel): /proc/driver/nvidia/version does not exist2022-03-07 19:06:12.381932: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "/media/ivysyn/tensorflow/synthesized/all-crashes/all/BoostedTreesMakeQuantileSummaries_d05507afa840c3185531b483b61bbe00.py", line 8, in <module>    tf.raw_ops.BoostedTreesMakeQuantileSummaries(float_values=float_values, example_weights=example_weights, epsilon=epsilon)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper    return f(**kwargs)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_boosted_trees_ops.py", line 1142, in boosted_trees_make_quantile_summaries    _ops.raise_from_not_ok_status(e, name)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status    raise core._status_to_exception(e) from None  # pylint: disable=protected-accesstensorflow.python.framework.errors_impl.InvalidArgumentError: Weights should be a single value or same size as features. [Op:BoostedTreesMakeQuantileSummaries]

# BoostedTreesMakeQuantileSummariesOp

import tensorflow as tf

float_values = tf.constant(1.2, shape=[6], dtype=tf.float32)
example_weights = tf.constant(1.2, shape=[6], dtype=tf.float32)
epsilon = tf.constant(1.2, shape=[6], dtype=tf.float32)
tf.raw_ops.BoostedTreesMakeQuantileSummaries(float_values=float_values, example_weights=example_weights, epsilon=epsilon)