# 2022-03-07 19:08:45.138905: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory2022-03-07 19:08:45.138964: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.2022-03-07 19:08:46.054356: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory2022-03-07 19:08:46.054417: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)2022-03-07 19:08:46.054436: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (devel): /proc/driver/nvidia/version does not exist2022-03-07 19:08:46.054712: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "/media/ivysyn/tensorflow/synthesized/all-crashes/all/RaggedGather_20befc697ab3504d7ef8fcc9ba266ae1.py", line 9, in <module>    tf.raw_ops.RaggedGather(params_nested_splits=params_nested_splits, params_dense_values=params_dense_values, indices=indices, OUTPUT_RAGGED_RANK=OUTPUT_RAGGED_RANK)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper    return f(**kwargs)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_ragged_array_ops.py", line 247, in ragged_gather    _ops.raise_from_not_ok_status(e, name)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status    raise core._status_to_exception(e) from None  # pylint: disable=protected-accesstensorflow.python.framework.errors_impl.InvalidArgumentError: Split tensors must not be scalars [Op:RaggedGather]

# RaggedGatherOpBase

import tensorflow as tf

OUTPUT_RAGGED_RANK = 2
params_nested_splits = tf.constant(0, shape=[5], dtype=tf.int64)
params_dense_values = tf.constant(1879048192, shape=[], dtype=tf.int64)
indices = tf.constant(-1879048192, shape=[7], dtype=tf.int32)
tf.raw_ops.RaggedGather(params_nested_splits=params_nested_splits, params_dense_values=params_dense_values, indices=indices, OUTPUT_RAGGED_RANK=OUTPUT_RAGGED_RANK)