# 2022-01-20 07:05:42.273703: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.2022-01-20 07:05:42.275813: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.Traceback (most recent call last):  File "/home/neo/mlfuzz/tensorflow/synthesized/all-crashes/all/Slice_804ef2c447ece462a399b962efd71d01.py", line 6, in <module>    tf.raw_ops.Slice(input=arg_0, begin=arg_1, size=arg_2)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper    return f(**kwargs)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9407, in _slice    _ops.raise_from_not_ok_status(e, name)  File "/home/neo/anaconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status    six.raise_from(core._status_to_exception(e.code, message), None)  File "<string>", line 3, in raise_fromtensorflow.python.framework.errors_impl.InvalidArgumentError: Expected begin and size arguments to be 1-D tensors of size 0, but got shapes [3] and [0] instead. [Op:Slice]

import tensorflow as tf

arg_0 = tf.constant(1250999896764, shape=[], dtype=tf.int64)
arg_1 = tf.constant(-536870912, shape=[3], dtype=tf.int32)
arg_2 = tf.constant([], shape=[0], dtype=tf.int32)
tf.raw_ops.Slice(input=arg_0, begin=arg_1, size=arg_2)