# Allocator
# 2022-01-31 11:00:32.058786: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.2022-01-31 11:00:32.060911: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 10007999174120 exceeds 10% of free system memory.2022-01-31 11:00:32.061143: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at sequence_ops.cc:80 : Resource exhausted: OOM when allocating tensor with shape[1250999896765] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpuTraceback (most recent call last):  File "/media/mlfuzz/tensorflow/synthesized/last-run-all/all/Range_b0f3edd8748df599262bdbfea4934234.py", line 6, in <module>    tf.raw_ops.Range(start=start, limit=limit, delta=delta)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper    return f(**kwargs)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 7360, in _range    _ops.raise_from_not_ok_status(e, name)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status    six.raise_from(core._status_to_exception(e.code, message), None)  File "<string>", line 3, in raise_fromtensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1250999896765] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Range]

import tensorflow as tf

start = tf.constant(-1250999896764, shape=[], dtype=tf.int64)
limit = tf.constant(1, shape=[], dtype=tf.int64)
delta = tf.constant(1, shape=[], dtype=tf.int64)
tf.raw_ops.Range(start=start, limit=limit, delta=delta)
