# 2022-01-28 15:27:16.461297: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 193, in make_type    v = dtypes.as_dtype(v).base_dtype  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 721, in as_dtype    raise TypeError("Cannot convert value %r to a TensorFlow DType." %TypeError: Cannot convert value <tf.Tensor: shape=(), dtype=int32, numpy=1879048192> to a TensorFlow DType.During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/media/mlfuzz/tensorflow/synthesized/last-run-all/all/StatelessMultinomial_68b7f3ecaaa9722a0a42f7f40c93edf3.py", line 8, in <module>    tf.raw_ops.StatelessMultinomial(logits=logits, num_samples=num_samples, seed=seed, output_dtype=output_dtype, name=name)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper    return f(**kwargs)  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_stateless_random_ops.py", line 54, in stateless_multinomial    return stateless_multinomial_eager_fallback(  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_stateless_random_ops.py", line 84, in stateless_multinomial_eager_fallback    output_dtype = _execute.make_type(output_dtype, "output_dtype")  File "/media/fuzzing-pytorch/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 195, in make_type    raise TypeError("Expected DataType for argument '%s' not %s." %TypeError: Expected DataType for argument 'output_dtype' not <tf.Tensor: shape=(), dtype=int32, numpy=1879048192>.

import tensorflow as tf

logits = tf.constant(-3.5e+35, shape=[1,3], dtype=tf.float32)
num_samples = tf.constant(-3.5e+35, shape=[1,3], dtype=tf.float32)
seed = tf.constant(1879048192, shape=[], dtype=tf.int32)
output_dtype = tf.constant(1879048192, shape=[], dtype=tf.int32)
name = tf.constant(-1250999896764, shape=[2], dtype=tf.int64)
tf.raw_ops.StatelessMultinomial(logits=logits, num_samples=num_samples, seed=seed, output_dtype=output_dtype, name=name)